### PR TITLE
feat(cleanup): clean some code

### PR DESCRIPTION
**Pull request by mezotv**
This cleans/fixes some code

- Fixed calculator command
- Added additional error handling
- Get the bot id from the token
- Only required used functions (fs, path)

### CODE REVIEW

**Comment by XanuduBuster** [comment]
@mezotv Won't this impact running it on replit?

**Comment by mezotv** [comment]
> 

I don't see how it would do that?

**Comment by AVVERSION** [comment]
I dont think so. It should work just fine with replit. There only seems to be some cleaning up

**Comment by XanuduBuster** [comment]
@mezotv We are hosting it on replit currently, and we are having some issues so we have to modify some stuffs

**Comment by XanuduBuster** [comment]
@AVVERSION should we merge this to OpenBot?

**Comment by mezotv** [comment]
> I dont think so. It should work just fine with replit. There only seems to be some cleaning up

Yea that's what I was thinking too.

**Comment by XanuduBuster** [comment]
Merging it now

**Comment by mezotv** [comment]
I have made another pull request as well to reduce storage used by GitHub #9

**Comment by AVVERSION** [comment]
> @AVVERSION should we merge this to OpenBot?

Yup, I think we should
Thank you @mezotv for the Pull Request!

**Pull request merged**
